// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: planetarymsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PLANetary.Communication.Protobuf {

  /// <summary>Holder for reflection information generated from planetarymsg.proto</summary>
  public static partial class PlanetarymsgReflection {

    #region Descriptor
    /// <summary>File descriptor for planetarymsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanetarymsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwbGFuZXRhcnltc2cucHJvdG8aFHF1ZXJ5YnJvYWRjYXN0LnByb3RvGhRx",
            "dWVyeXBhcmVudHNlbC5wcm90bxoPcmVzdWx0c2V0LnByb3RvGhFjYW5jZWxx",
            "dWVyeS5wcm90byK2AQoQUGxhbmV0YXJ5TWVzc2FnZRIkCglicm9hZGNhc3QY",
            "ASABKAsyDy5RdWVyeUJyb2FkY2FzdEgAEiQKCXBhcmVudHNlbBgCIAEoCzIP",
            "LlF1ZXJ5UGFyZW50U2VsSAASHwoJcmVzdWx0c2V0GAMgASgLMgouUmVzdWx0",
            "c2V0SAASKgoLY2FuY2VscXVlcnkYBCABKAsyEy5DYW5jZWxRdWVyeU1lc3Nh",
            "Z2VIAEIJCgdwYXlsb2FkQiOqAiBQTEFOZXRhcnkuQ29tbXVuaWNhdGlvbi5Q",
            "cm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PLANetary.Communication.Protobuf.QuerybroadcastReflection.Descriptor, global::PLANetary.Communication.Protobuf.QueryparentselReflection.Descriptor, global::PLANetary.Communication.Protobuf.ResultsetReflection.Descriptor, global::PLANetary.Communication.Protobuf.CancelqueryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PLANetary.Communication.Protobuf.PlanetaryMessage), global::PLANetary.Communication.Protobuf.PlanetaryMessage.Parser, new[]{ "Broadcast", "Parentsel", "Resultset", "Cancelquery" }, new[]{ "Payload" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlanetaryMessage : pb::IMessage<PlanetaryMessage> {
    private static readonly pb::MessageParser<PlanetaryMessage> _parser = new pb::MessageParser<PlanetaryMessage>(() => new PlanetaryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlanetaryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLANetary.Communication.Protobuf.PlanetarymsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlanetaryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlanetaryMessage(PlanetaryMessage other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.Broadcast:
          Broadcast = other.Broadcast.Clone();
          break;
        case PayloadOneofCase.Parentsel:
          Parentsel = other.Parentsel.Clone();
          break;
        case PayloadOneofCase.Resultset:
          Resultset = other.Resultset.Clone();
          break;
        case PayloadOneofCase.Cancelquery:
          Cancelquery = other.Cancelquery.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlanetaryMessage Clone() {
      return new PlanetaryMessage(this);
    }

    /// <summary>Field number for the "broadcast" field.</summary>
    public const int BroadcastFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.QueryBroadcast Broadcast {
      get { return payloadCase_ == PayloadOneofCase.Broadcast ? (global::PLANetary.Communication.Protobuf.QueryBroadcast) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Broadcast;
      }
    }

    /// <summary>Field number for the "parentsel" field.</summary>
    public const int ParentselFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.QueryParentSel Parentsel {
      get { return payloadCase_ == PayloadOneofCase.Parentsel ? (global::PLANetary.Communication.Protobuf.QueryParentSel) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Parentsel;
      }
    }

    /// <summary>Field number for the "resultset" field.</summary>
    public const int ResultsetFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.Resultset Resultset {
      get { return payloadCase_ == PayloadOneofCase.Resultset ? (global::PLANetary.Communication.Protobuf.Resultset) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Resultset;
      }
    }

    /// <summary>Field number for the "cancelquery" field.</summary>
    public const int CancelqueryFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.CancelQueryMessage Cancelquery {
      get { return payloadCase_ == PayloadOneofCase.Cancelquery ? (global::PLANetary.Communication.Protobuf.CancelQueryMessage) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Cancelquery;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Broadcast = 1,
      Parentsel = 2,
      Resultset = 3,
      Cancelquery = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlanetaryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlanetaryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Broadcast, other.Broadcast)) return false;
      if (!object.Equals(Parentsel, other.Parentsel)) return false;
      if (!object.Equals(Resultset, other.Resultset)) return false;
      if (!object.Equals(Cancelquery, other.Cancelquery)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Broadcast) hash ^= Broadcast.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Parentsel) hash ^= Parentsel.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Resultset) hash ^= Resultset.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Cancelquery) hash ^= Cancelquery.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (payloadCase_ == PayloadOneofCase.Broadcast) {
        output.WriteRawTag(10);
        output.WriteMessage(Broadcast);
      }
      if (payloadCase_ == PayloadOneofCase.Parentsel) {
        output.WriteRawTag(18);
        output.WriteMessage(Parentsel);
      }
      if (payloadCase_ == PayloadOneofCase.Resultset) {
        output.WriteRawTag(26);
        output.WriteMessage(Resultset);
      }
      if (payloadCase_ == PayloadOneofCase.Cancelquery) {
        output.WriteRawTag(34);
        output.WriteMessage(Cancelquery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Broadcast) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Broadcast);
      }
      if (payloadCase_ == PayloadOneofCase.Parentsel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Parentsel);
      }
      if (payloadCase_ == PayloadOneofCase.Resultset) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resultset);
      }
      if (payloadCase_ == PayloadOneofCase.Cancelquery) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cancelquery);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlanetaryMessage other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Broadcast:
          if (Broadcast == null) {
            Broadcast = new global::PLANetary.Communication.Protobuf.QueryBroadcast();
          }
          Broadcast.MergeFrom(other.Broadcast);
          break;
        case PayloadOneofCase.Parentsel:
          if (Parentsel == null) {
            Parentsel = new global::PLANetary.Communication.Protobuf.QueryParentSel();
          }
          Parentsel.MergeFrom(other.Parentsel);
          break;
        case PayloadOneofCase.Resultset:
          if (Resultset == null) {
            Resultset = new global::PLANetary.Communication.Protobuf.Resultset();
          }
          Resultset.MergeFrom(other.Resultset);
          break;
        case PayloadOneofCase.Cancelquery:
          if (Cancelquery == null) {
            Cancelquery = new global::PLANetary.Communication.Protobuf.CancelQueryMessage();
          }
          Cancelquery.MergeFrom(other.Cancelquery);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::PLANetary.Communication.Protobuf.QueryBroadcast subBuilder = new global::PLANetary.Communication.Protobuf.QueryBroadcast();
            if (payloadCase_ == PayloadOneofCase.Broadcast) {
              subBuilder.MergeFrom(Broadcast);
            }
            input.ReadMessage(subBuilder);
            Broadcast = subBuilder;
            break;
          }
          case 18: {
            global::PLANetary.Communication.Protobuf.QueryParentSel subBuilder = new global::PLANetary.Communication.Protobuf.QueryParentSel();
            if (payloadCase_ == PayloadOneofCase.Parentsel) {
              subBuilder.MergeFrom(Parentsel);
            }
            input.ReadMessage(subBuilder);
            Parentsel = subBuilder;
            break;
          }
          case 26: {
            global::PLANetary.Communication.Protobuf.Resultset subBuilder = new global::PLANetary.Communication.Protobuf.Resultset();
            if (payloadCase_ == PayloadOneofCase.Resultset) {
              subBuilder.MergeFrom(Resultset);
            }
            input.ReadMessage(subBuilder);
            Resultset = subBuilder;
            break;
          }
          case 34: {
            global::PLANetary.Communication.Protobuf.CancelQueryMessage subBuilder = new global::PLANetary.Communication.Protobuf.CancelQueryMessage();
            if (payloadCase_ == PayloadOneofCase.Cancelquery) {
              subBuilder.MergeFrom(Cancelquery);
            }
            input.ReadMessage(subBuilder);
            Cancelquery = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
