// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: queryparentsel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PLANetary.Communication.Protobuf {

  /// <summary>Holder for reflection information generated from queryparentsel.proto</summary>
  public static partial class QueryparentselReflection {

    #region Descriptor
    /// <summary>File descriptor for queryparentsel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryparentselReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRxdWVyeXBhcmVudHNlbC5wcm90bxoQaWRlbnRpZmllci5wcm90byJFCg5R",
            "dWVyeVBhcmVudFNlbBIZCgdxdWVyeUlkGAEgASgLMgguUXVlcnlJZBIYCgdj",
            "aGlsZElkGAIgASgLMgcuTm9kZUlkQiOqAiBQTEFOZXRhcnkuQ29tbXVuaWNh",
            "dGlvbi5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PLANetary.Communication.Protobuf.IdentifierReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PLANetary.Communication.Protobuf.QueryParentSel), global::PLANetary.Communication.Protobuf.QueryParentSel.Parser, new[]{ "QueryId", "ChildId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QueryParentSel : pb::IMessage<QueryParentSel> {
    private static readonly pb::MessageParser<QueryParentSel> _parser = new pb::MessageParser<QueryParentSel>(() => new QueryParentSel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryParentSel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PLANetary.Communication.Protobuf.QueryparentselReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryParentSel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryParentSel(QueryParentSel other) : this() {
      queryId_ = other.queryId_ != null ? other.queryId_.Clone() : null;
      childId_ = other.childId_ != null ? other.childId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryParentSel Clone() {
      return new QueryParentSel(this);
    }

    /// <summary>Field number for the "queryId" field.</summary>
    public const int QueryIdFieldNumber = 1;
    private global::PLANetary.Communication.Protobuf.QueryId queryId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.QueryId QueryId {
      get { return queryId_; }
      set {
        queryId_ = value;
      }
    }

    /// <summary>Field number for the "childId" field.</summary>
    public const int ChildIdFieldNumber = 2;
    private global::PLANetary.Communication.Protobuf.NodeId childId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PLANetary.Communication.Protobuf.NodeId ChildId {
      get { return childId_; }
      set {
        childId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryParentSel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryParentSel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(QueryId, other.QueryId)) return false;
      if (!object.Equals(ChildId, other.ChildId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (queryId_ != null) hash ^= QueryId.GetHashCode();
      if (childId_ != null) hash ^= ChildId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (queryId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(QueryId);
      }
      if (childId_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChildId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (queryId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(QueryId);
      }
      if (childId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChildId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryParentSel other) {
      if (other == null) {
        return;
      }
      if (other.queryId_ != null) {
        if (queryId_ == null) {
          queryId_ = new global::PLANetary.Communication.Protobuf.QueryId();
        }
        QueryId.MergeFrom(other.QueryId);
      }
      if (other.childId_ != null) {
        if (childId_ == null) {
          childId_ = new global::PLANetary.Communication.Protobuf.NodeId();
        }
        ChildId.MergeFrom(other.ChildId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (queryId_ == null) {
              queryId_ = new global::PLANetary.Communication.Protobuf.QueryId();
            }
            input.ReadMessage(queryId_);
            break;
          }
          case 18: {
            if (childId_ == null) {
              childId_ = new global::PLANetary.Communication.Protobuf.NodeId();
            }
            input.ReadMessage(childId_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
