/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.9 */

#include <planetary/proto/condition.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConditionGroup_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ConditionGroup, conditionLink, conditionLink, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, ConditionGroup, conditions, conditionLink, &Condition_fields),
    PB_LAST_FIELD
};

const pb_field_t Condition_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, Condition, identifier, identifier, &Identifier_fields),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Condition, op, identifier, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, Condition, value, op, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ConditionGroup, conditions[0]) < 65536 && pb_membersize(Condition, identifier) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ConditionGroup_Condition)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ConditionGroup, conditions[0]) < 256 && pb_membersize(Condition, identifier) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ConditionGroup_Condition)
#endif


/* @@protoc_insertion_point(eof) */
