/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.9 */

#include <planetary/proto/identifier.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Identifier_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Identifier, name, name, 0),
    PB_LAST_FIELD
};

const pb_field_t QueryId_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, QueryId, shortId, shortId, 0),
    PB_LAST_FIELD
};

const pb_field_t NodeId_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, NodeId, shortId, shortId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
