/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.9 */

#include <planetary/proto/planetarymsg.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PlanetaryMessage_fields[6] = {
    PB_ONEOF_FIELD(payload,   1, MESSAGE , ONEOF, STATIC  , FIRST, PlanetaryMessage, broadcast, broadcast, &QueryBroadcast_fields),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , UNION, PlanetaryMessage, parentsel, parentsel, &QueryParentSel_fields),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , UNION, PlanetaryMessage, resultset, resultset, &Resultset_fields),
    PB_ONEOF_FIELD(payload,   4, MESSAGE , ONEOF, STATIC  , UNION, PlanetaryMessage, cancelquery, cancelquery, &CancelQueryMessage_fields),
    PB_ONEOF_FIELD(payload,   5, MESSAGE , ONEOF, STATIC  , UNION, PlanetaryMessage, store, store, &Store_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PlanetaryMessage, payload.broadcast) < 65536 && pb_membersize(PlanetaryMessage, payload.parentsel) < 65536 && pb_membersize(PlanetaryMessage, payload.resultset) < 65536 && pb_membersize(PlanetaryMessage, payload.cancelquery) < 65536 && pb_membersize(PlanetaryMessage, payload.store) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PlanetaryMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PlanetaryMessage, payload.broadcast) < 256 && pb_membersize(PlanetaryMessage, payload.parentsel) < 256 && pb_membersize(PlanetaryMessage, payload.resultset) < 256 && pb_membersize(PlanetaryMessage, payload.cancelquery) < 256 && pb_membersize(PlanetaryMessage, payload.store) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PlanetaryMessage)
#endif


/* @@protoc_insertion_point(eof) */
