/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.9 */

#include <planetary/proto/query.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Query_fields[7] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, Query, queryId, queryId, &QueryId_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Query, periodInSec, queryId, 0),
    PB_FIELD(  3, ENUM    , SINGULAR, STATIC  , OTHER, Query, conditionGroupLink, periodInSec, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, Query, conditionGroups, conditionGroupLink, &ConditionGroup_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, Query, actions, conditionGroups, &Action_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, Query, resultTarget, actions, &ResultTarget_fields),
    PB_LAST_FIELD
};

const pb_field_t ResultTarget_fields[3] = {
    PB_ONEOF_FIELD(target,   1, MESSAGE , ONEOF, STATIC  , FIRST, ResultTarget, sink, sink, &SinkTarget_fields),
    PB_ONEOF_FIELD(target,   2, MESSAGE , ONEOF, STATIC  , UNION, ResultTarget, storeTarget, storeTarget, &StoreTarget_fields),
    PB_LAST_FIELD
};

const pb_field_t SinkTarget_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t StoreTarget_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, StoreTarget, storeName, storeName, 0),
    PB_LAST_FIELD
};

const pb_field_t Action_fields[5] = {
    PB_ONEOF_FIELD(content,   1, MESSAGE , ONEOF, STATIC  , FIRST, Action, selector, selector, &Selector_fields),
    PB_ONEOF_FIELD(content,   2, MESSAGE , ONEOF, STATIC  , UNION, Action, actor, actor, &Actor_fields),
    PB_ONEOF_FIELD(content,   3, MESSAGE , ONEOF, STATIC  , UNION, Action, event, event, &Event_fields),
    PB_ONEOF_FIELD(content,   4, MESSAGE , ONEOF, STATIC  , UNION, Action, store, store, &Store_fields),
    PB_LAST_FIELD
};

const pb_field_t Selector_fields[4] = {
    PB_ONEOF_FIELD(source,   1, MESSAGE , ONEOF, STATIC  , FIRST, Selector, sensor, sensor, &SensorSource_fields),
    PB_ONEOF_FIELD(source,   2, MESSAGE , ONEOF, STATIC  , UNION, Selector, store, store, &StoreSource_fields),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, Selector, type, source.store, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorSource_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, SensorSource, sensorId, sensorId, &Identifier_fields),
    PB_LAST_FIELD
};

const pb_field_t StoreSource_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, StoreSource, storeName, storeName, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, StoreSource, param, storeName, 0),
    PB_LAST_FIELD
};

const pb_field_t Actor_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, Actor, actorId, actorId, &Identifier_fields),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Actor, param, actorId, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, Event, eventId, eventId, &Identifier_fields),
    PB_LAST_FIELD
};






/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Query, queryId) < 65536 && pb_membersize(Query, conditionGroups[0]) < 65536 && pb_membersize(Query, actions[0]) < 65536 && pb_membersize(Query, resultTarget) < 65536 && pb_membersize(ResultTarget, target.sink) < 65536 && pb_membersize(ResultTarget, target.storeTarget) < 65536 && pb_membersize(Action, content.selector) < 65536 && pb_membersize(Action, content.actor) < 65536 && pb_membersize(Action, content.event) < 65536 && pb_membersize(Action, content.store) < 65536 && pb_membersize(Selector, source.sensor) < 65536 && pb_membersize(Selector, source.store) < 65536 && pb_membersize(SensorSource, sensorId) < 65536 && pb_membersize(Actor, actorId) < 65536 && pb_membersize(Event, eventId) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Query_ResultTarget_SinkTarget_StoreTarget_Action_Selector_SensorSource_StoreSource_Actor_Event)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Query, queryId) < 256 && pb_membersize(Query, conditionGroups[0]) < 256 && pb_membersize(Query, actions[0]) < 256 && pb_membersize(Query, resultTarget) < 256 && pb_membersize(ResultTarget, target.sink) < 256 && pb_membersize(ResultTarget, target.storeTarget) < 256 && pb_membersize(Action, content.selector) < 256 && pb_membersize(Action, content.actor) < 256 && pb_membersize(Action, content.event) < 256 && pb_membersize(Action, content.store) < 256 && pb_membersize(Selector, source.sensor) < 256 && pb_membersize(Selector, source.store) < 256 && pb_membersize(SensorSource, sensorId) < 256 && pb_membersize(Actor, actorId) < 256 && pb_membersize(Event, eventId) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Query_ResultTarget_SinkTarget_StoreTarget_Action_Selector_SensorSource_StoreSource_Actor_Event)
#endif


/* @@protoc_insertion_point(eof) */
