/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.9 */

#ifndef PB_CANCELQUERY_PB_H_INCLUDED
#define PB_CANCELQUERY_PB_H_INCLUDED
#include <nanopb/pb.h>
#include <planetary/proto/identifier.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CancelQueryMessage {
    QueryId queryId;
/* @@protoc_insertion_point(struct:CancelQueryMessage) */
} CancelQueryMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define CancelQueryMessage_init_default          {QueryId_init_default}
#define CancelQueryMessage_init_zero             {QueryId_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define CancelQueryMessage_queryId_tag           1

/* Struct field encoding specification for nanopb */
extern const pb_field_t CancelQueryMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define CancelQueryMessage_size                  (6 + QueryId_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CANCELQUERY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
