/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 */

#ifndef PB_QUERYPARENTSEL_PB_H_INCLUDED
#define PB_QUERYPARENTSEL_PB_H_INCLUDED
#include <nanopb/pb.h>
#include <planetary/proto/identifier.pb.h>
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _QueryParentSel {
    QueryId queryId;
    NodeId childId;
/* @@protoc_insertion_point(struct:QueryParentSel) */
} QueryParentSel;

/* Default values for struct fields */

/* Initializer values for message structs */
#define QueryParentSel_init_default              {QueryId_init_default, NodeId_init_default}
#define QueryParentSel_init_zero                 {QueryId_init_zero, NodeId_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define QueryParentSel_queryId_tag               1
#define QueryParentSel_childId_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t QueryParentSel_fields[3];

/* Maximum encoded size of messages (where known) */
#define QueryParentSel_size                      (12 + QueryId_size + NodeId_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define QUERYPARENTSEL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
